# Using MultinomialNB()

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd


# 1. Load Data (SMS Spam Collection)
ratings = "/Users/suraj/Downloads/Ratings.csv";
df_ratings = pd.read_csv(ratings)

In [2]:
df_ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [3]:
df_ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  str
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), str(1)
memory usage: 37.3 MB

In [4]:
df_ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [5]:
df_ratings.duplicated().sum()

np.int64(0)

In [6]:
df_ratings = df_ratings.drop_duplicates()

In [7]:
df_ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='str')

In [8]:
bins = [-1, 3, 7, 10]
labels = ['Negative', 'Neutral', 'Positive']

df_ratings['Book_Class'] = pd.cut(df_ratings['Book-Rating'], bins=bins, labels=labels)

print(df_ratings[['Book-Rating', 'Book_Class']].head())

   Book-Rating Book_Class
0            0   Negative
1            5    Neutral
2            0   Negative
3            3   Negative
4            6    Neutral

In [9]:
df_ratings

         User-ID         ISBN  Book-Rating Book_Class
0         276725   034545104X            0   Negative
1         276726   0155061224            5    Neutral
2         276727   0446520802            0   Negative
3         276729   052165615X            3   Negative
4         276729   0521795028            6    Neutral
...          ...          ...          ...        ...
1149775   276704   1563526298            9   Positive
1149776   276706   0679447156            0   Negative
1149777   276709   0515107662           10   Positive
1149778   276721   0590442449           10   Positive
1149779   276723  05162443314            8   Positive

[1149780 rows x 4 columns]

In [10]:
df_ratings['Book_Class_num'] = df_ratings['Book_Class'].map({
    'Negative': 0, 
    'Neutral': 1, 
    'Positive': 2
})

In [11]:
df_ratings

         User-ID         ISBN  Book-Rating Book_Class Book_Class_num
0         276725   034545104X            0   Negative              0
1         276726   0155061224            5    Neutral              1
2         276727   0446520802            0   Negative              0
3         276729   052165615X            3   Negative              0
4         276729   0521795028            6    Neutral              1
...          ...          ...          ...        ...            ...
1149775   276704   1563526298            9   Positive              2
1149776   276706   0679447156            0   Negative              0
1149777   276709   0515107662           10   Positive              2
1149778   276721   0590442449           10   Positive              2
1149779   276723  05162443314            8   Positive              2

[1149780 rows x 5 columns]

In [12]:
X = df_ratings['ISBN']
y = df_ratings['Book_Class_num']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)      

nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [14]:
y_pred = nb.predict(X_test_dtm)

In [15]:

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[139681    472   5216]
 [ 33030    177   1346]
 [ 47055    150   2829]]

Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.96      0.77    145369
           1       0.22      0.01      0.01     34553
           2       0.30      0.06      0.10     50034

    accuracy                           0.62    229956
   macro avg       0.39      0.34      0.29    229956
weighted avg       0.50      0.62      0.51    229956

In [16]:
df_ratings[['ISBN','Book_Class_num']]

                ISBN Book_Class_num
0         034545104X              0
1         0155061224              1
2         0446520802              0
3         052165615X              0
4         0521795028              1
...              ...            ...
1149775   1563526298              2
1149776   0679447156              0
1149777   0515107662              2
1149778   0590442449              2
1149779  05162443314              2

[1149780 rows x 2 columns]

In [17]:
df_ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 5 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   User-ID         1149780 non-null  int64
 1   ISBN            1149780 non-null  str
 2   Book-Rating     1149780 non-null  int64
 3   Book_Class      1149780 non-null  category
 4   Book_Class_num  1149780 non-null  category
dtypes: category(2), int64(2), str(1)
memory usage: 39.5 MB

In [18]:
df_ratings['Book_Class_num'] = df_ratings['Book_Class_num'].astype(int)

In [19]:
df_ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 5 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   User-ID         1149780 non-null  int64
 1   ISBN            1149780 non-null  str
 2   Book-Rating     1149780 non-null  int64
 3   Book_Class      1149780 non-null  category
 4   Book_Class_num  1149780 non-null  int64
dtypes: category(1), int64(3), str(1)
memory usage: 47.2 MB

In [20]:
total_rows = len(df_ratings["Book_Class_num"])

counts = df_ratings["Book_Class_num"].value_counts()

print(f"Total rows: {total_rows}")
print("--- Counts per category ---")
print(counts)

Total rows: 1149780
--- Counts per category ---
Book_Class_num
0    726634
2    249887
1    173259
Name: count, dtype: int64

In [21]:
custom_isbn = ["034545104X","0155061224","1563526298","05162443314","0590442449","0515107662","342310538"] 

custom_vec = vect.transform(custom_isbn)

prediction = nb.predict(custom_vec)

print(f"Prediction for '{custom_isbn[0]}': {'Positive' if nb.predict(custom_vec)[0]==2 else ('Neutral' if nb.predict(custom_vec)[0]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[1]}': {'Positive' if nb.predict(custom_vec)[1]==2 else ('Neutral' if nb.predict(custom_vec)[1]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[2]}': {'Positive' if nb.predict(custom_vec)[2]==2 else ('Neutral' if nb.predict(custom_vec)[2]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[3]}': {'Positive' if nb.predict(custom_vec)[3]==2 else ('Neutral' if nb.predict(custom_vec)[3]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[4]}': {'Positive' if nb.predict(custom_vec)[4]==2 else ('Neutral' if nb.predict(custom_vec)[4]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[5]}': {'Positive' if nb.predict(custom_vec)[5]==2 else ('Neutral' if nb.predict(custom_vec)[5]==1 else 'Negative')}")
print(f"Prediction for '{custom_isbn[6]}': {'Positive' if nb.predict(custom_vec)[6]==2 else ('Neutral' if nb.predict(custom_vec)[6]==1 else 'Negative')}")

Prediction for '034545104X': Negative
Prediction for '0155061224': Negative
Prediction for '1563526298': Positive
Prediction for '05162443314': Positive
Prediction for '0590442449': Negative
Prediction for '0515107662': Negative
Prediction for '342310538': Negative

In [22]:
book_data = df_ratings[df_ratings["ISBN"] == "342310538"]
print(book_data)

average_rating = book_data["Book-Rating"].mean()
print(f"The average rating for this book is: {average_rating}")

         User-ID       ISBN  Book-Rating Book_Class  Book_Class_num
9         276745  342310538           10   Positive               2
1070832   255906  342310538            0   Negative               0
The average rating for this book is: 5.0

In [23]:
custom_isbn = ["034545104X","0155061224","1563526298","05162443314","0590442449","0515107662","342310538","8440682697"] 

# 1. Transform and Predict all at once
custom_vec = vect.transform(custom_isbn)
predictions = nb.predict(custom_vec)  # This returns an array of numbers

class_map = {0: 'Negative', 1: 'Neutral', 2: 'Positive'}

# 2. Use zip to pair each ISBN with its specific prediction
for isbn, pred_num in zip(custom_isbn, predictions):
    label = class_map[pred_num]
    print(f"The model predicts ISBN {isbn} is: {label}")

The model predicts ISBN 034545104X is: Negative
The model predicts ISBN 0155061224 is: Negative
The model predicts ISBN 1563526298 is: Positive
The model predicts ISBN 05162443314 is: Positive
The model predicts ISBN 0590442449 is: Negative
The model predicts ISBN 0515107662 is: Negative
The model predicts ISBN 342310538 is: Negative
The model predicts ISBN 8440682697 is: Positive

# Using ComplementNB()

In [62]:
ratings = "/Users/suraj/Downloads/Ratings.csv";
df = pd.read_csv(ratings , encoding='utf-8')

In [63]:
df

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [26]:
#df = df[df['ISBN'].str.contains(r'^[a-zA-Z0-9]', na=False)]

In [27]:
#df['ISBN'] = df['ISBN'].str.strip()

In [28]:
#df = df[df['ISBN'].str.match(r'^[0-9X]+$')]

In [29]:
df

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [66]:
# Keep only rows where the ISBN contains digits
df = df[df['ISBN'].astype(str).str.contains(r'\d', na=False)]

In [67]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ISBN_encoded'] = le.fit_transform(df['ISBN'])

In [68]:
print(f"Classes: {le.classes_[-1]}") #doubt

Classes: ´3499128624

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 4 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   User-ID       1149780 non-null  int64
 1   ISBN          1149780 non-null  str
 2   Book-Rating   1149780 non-null  int64
 3   ISBN_encoded  1149780 non-null  int64
dtypes: int64(3), str(1)
memory usage: 46.1 MB

In [33]:
df.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'ISBN_encoded'], dtype='str')

In [34]:
correlation_matrix = df[['User-ID','Book-Rating', 'ISBN_encoded']].corr()
print(correlation_matrix)

               User-ID  Book-Rating  ISBN_encoded
User-ID       1.000000    -0.046944     -0.017062
Book-Rating  -0.046944     1.000000      0.042945
ISBN_encoded -0.017062     0.042945      1.000000

In [69]:
rating_map = {
    0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0,  # 0-5 become 0 (Negative)
    6: 1, 7: 1, 8: 1, 9: 1, 10: 1       # 6-10 become 1 (Positive)
}

df['Book-Ratings_Sentiment'] = df['Book-Rating'].map(rating_map)

In [36]:
df

,User-ID,ISBN,Book-Rating,ISBN_encoded,Book-Ratings_Sentiment
0,276725,034545104X,0,57188,0
1,276726,0155061224,5,29750,0
2,276727,0446520802,0,107392,0
3,276729,052165615X,3,127253,0
4,276729,0521795028,6,127287,1
...,...,...,...,...,...
1149775,276704,1563526298,9,256876,1
1149776,276706,0679447156,0,164861,0
1149777,276709,0515107662,10,123711,1
1149778,276721,0590442449,10,145625,1
1149779,276723,05162443314,8,124712,1

In [70]:
X = df['ISBN']
y = df['Book-Ratings_Sentiment']

In [71]:
from sklearn.naive_bayes import ComplementNB

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vect = CountVectorizer()

model_train = vect.fit_transform(X_train) 
model_test = vect.transform(X_test)      

nb = ComplementNB()
nb.fit(model_train, y_train)

ComplementNB()

In [73]:
y_pred = nb.predict(model_test)

In [74]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[114818  42536]
 [ 47239  25352]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.73      0.72    157354
           1       0.37      0.35      0.36     72591

    accuracy                           0.61    229945
   macro avg       0.54      0.54      0.54    229945
weighted avg       0.60      0.61      0.61    229945

In [75]:
df

,User-ID,ISBN,Book-Rating,ISBN_encoded,Book-Ratings_Sentiment
0,276725,034545104X,0,57187,0
1,276726,0155061224,5,29749,0
2,276727,0446520802,0,107391,0
3,276729,052165615X,3,127252,0
4,276729,0521795028,6,127286,1
...,...,...,...,...,...
1149775,276704,1563526298,9,256875,1
1149776,276706,0679447156,0,164860,0
1149777,276709,0515107662,10,123710,1
1149778,276721,0590442449,10,145624,1
1149779,276723,05162443314,8,124711,1

In [76]:
total_rows = len(df["Book-Ratings_Sentiment"])

counts = df["Book-Ratings_Sentiment"].value_counts()

print(f"Total rows: {total_rows}")
print("--- Counts per category ---")
print(counts)

Total rows: 1149722
--- Counts per category ---
Book-Ratings_Sentiment
0    786472
1    363250
Name: count, dtype: int64

In [77]:
custom_isbn = ["034545104X","0155061224","1563526298","05162443314","0590442449","0515107662","342310538","8440682697"] 

custom_vec = vect.transform(custom_isbn)
predictions = nb.predict(custom_vec)  # This returns an array of numbers

class_map = {0: 'Negative', 1: 'Positive'}

for isbn, pred_num in zip(custom_isbn, predictions):
    label = class_map[pred_num]
    print(f"The model predicts ISBN {isbn} is: {label}")

The model predicts ISBN 034545104X is: Negative
The model predicts ISBN 0155061224 is: Negative
The model predicts ISBN 1563526298 is: Positive
The model predicts ISBN 05162443314 is: Positive
The model predicts ISBN 0590442449 is: Negative
The model predicts ISBN 0515107662 is: Positive
The model predicts ISBN 342310538 is: Positive
The model predicts ISBN 8440682697 is: Positive

In [79]:
book_data = df[df["ISBN"] == "342310538"]
print(book_data)

         User-ID       ISBN  Book-Rating  ISBN_encoded  Book-Ratings_Sentiment
9         276745  342310538           10        292988                       1
1070832   255906  342310538            0        292988                       0