# The Core Definition

## Model Parameters
These are the internal variables that the model **learns automatically** from the training data.  
The data scientist does **not** set these manually.  

They are the **output of the learning process**.

Examples:
- Weights in Linear Regression
- Coefficients in Logistic Regression
- Weights and biases in Neural Networks
- Split thresholds in Decision Trees


---

## Hyperparameters
These are the **external configuration settings** that the data scientist sets **before the training process begins**.  

They guide **how the model learns**.

Examples:
- Learning rate
- Number of trees in Random Forest
- Maximum depth of a tree
- Number of hidden layers in a Neural Network
- Regularization strength (λ)


---

## Key Difference

| Model Parameters | Hyperparameters |
|------------------|------------------|
| Learned automatically | Set manually before training |
| Internal to the model | External configuration |
| Output of training | Input to training |
| Example: weights | Example: learning rate |

### Hyperparameters Control

They control:

- 🧠 **Model complexity**
- ⚡ **Training speed**
- 🎯 **Accuracy**
- 🚫 **Overfitting**

### Hyperparameters Control

They control:

- 🧠 **Model complexity**
- ⚡ **Training speed**
- 🎯 **Accuracy**
- 🚫 **Overfitting**

# Examples: Parameters vs Hyperparameters

---

## 1️⃣ Linear Regression

### Parameters:
- The weights ($w_1, w_2, \dots, w_n$)
- The bias ($b$)

The model calculates these automatically during training  
(e.g., using **Ordinary Least Squares**).

### Hyperparameters:
- If using Gradient Descent → the **Learning Rate ($\alpha$)**  

You must set this **before training begins**.

---

## 2️⃣ Decision Trees

### Parameters:
- The actual decision rules at each node  
  (e.g., *"Is Age > 25?"*, *"Is Income < $50k?"*)

The model determines these splits based on the data.

### Hyperparameters:
- **Maximum Depth (`max_depth`)**

You decide beforehand how deep the tree can grow  
(e.g., maximum 5 levels).

---

# 1.2 The Need for Tuning: Underfitting vs Overfitting

## 🎯 The Goal

Why do we care about hyperparameters?

Because they control **how complex a model is**.

If the model is:
- Too simple → **Underfitting**
- Too complex → **Overfitting**
- Just right → **Good Fit**

Tuning helps us find the **best balance**.

---





## 💡 Easy Analogy: Student Studying for an Exam

### 📉 Underfitting (Too Simple)
A student only reads the chapter titles and goes to sleep.  
They fail because they didn't study enough.

👉 The model didn’t learn enough patterns.

---

### 📈 Overfitting (Too Complex)
A student memorizes answers from one practice test word-for-word.  
In the real exam, numbers change slightly — they fail.

👉 The model memorized training data instead of understanding patterns.

---

### ✅ Good Fit (Tuned Properly)
A student understands the formulas and concepts.  
They can solve new problems easily.

👉 The model learns general patterns that work on new data.

---

## 🛠️ Example: `max_depth` in a Decision Tree

### 🌳 max_depth = 1
- Very small tree
- Too simple
- Result → **Underfitting**

---

### 🌳 max_depth = None
- Tree grows until it memorizes everything
- Perfect on training data
- Poor on new data
- Result → **Overfitting**

---

### 🌳 max_depth = 5
- Balanced complexity
- Captures important patterns
- Ignores random noise
- Result → **Good Fit**

---

# Understanding Underfitting, Good Fit, and Overfitting

---

## 📉 Left Side – Underfitting (bad on both training and testing)

- **Model is too simple**
- **High bias**
- **Poor performance** on training and testing data
- **Example:** Linear model trying to fit complex data


---

## ✅ Middle – Good Fit (Optimal Model)

- **Balanced bias and variance**
- **Learns patterns properly**
- **Performs well** on unseen data
- **Best generalization**

💡 *This is the goal of training.*

---

## 📈 Right Side – Overfitting  (great on training, bad on testing)

- **Model is too complex**
- **Memorizes training data**
- **High variance**
- **Poor performance** on new data
- **Example:** Deep neural network on small dataset


---

# 1.3 The Curse of Dimensionality in Hyperparameter Tuning

---

## 🎯 The Goal
To understand **why we can't just try every possible hyperparameter** and why tuning can take a lot of time.

---

## 📖 The Core Concept
**The Curse of Dimensionality** means:  
> As you add more hyperparameters to tune, the number of combinations grows **exponentially**.  

Checking every combination (brute force) **quickly becomes impossible**.

---

## 💡 Analogy: The Combination Padlock
- **1 dial (0-9):** 10 tries max  
- **3 dials:** 10 × 10 × 10 = 1,000 tries  
- **5 dials:** 10 × 10 × 10 × 10 × 10 = 100,000 tries  

> Every new dial (hyperparameter) **multiplies the work**.

---

## 🛠️ Mathematical Example

Suppose we tune a **Random Forest Classifier** with these options:

| Hyperparameter | Options |
|----------------|---------|
| n_estimators | 10, 50, 100, 200, 500 (5 options) |
| max_depth | None, 10, 20, 30 (4 options) |
| min_samples_split | 2, 5, 10, 15, 20 (5 options) |


**Total combinations:**  

5 × 4 × 5  = 100 unique models


Using **5-Fold Cross-Validation**:  


100 combinations × 5 folds = 500 model trainings



If **1 model takes 1 minute**, the total time = **8.33 hours**!  
Add one more hyperparameter with 10 options → **83.3 hours (~3, 4 days)**!

---

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [10, 50, 100, 200, 500],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10, 15, 20]
}

# Initialize RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,              # 5-Fold Cross Validation
    n_jobs=-1,         # Use all CPU cores
    verbose=2         # Prints progress
)

# Fit the Grid Search to your training data
grid_search.fit(X_train, y_train)

# Best combination found
print("Best Hyperparameters:", grid_search.best_params_)
print("Best Cross-Validation Score:", grid_search.best_score_)

NameError: name 'X_train' is not defined

# Module 2: Cross-Validation (The Foundation)

---

## **2.1 What is Cross-Validation?**  
Cross-validation is a technique to **evaluate how well your model will perform on unseen data**.  

- The simple **train-test split** divides your dataset once into a training set and a test set.  
- Problem: The model’s performance depends heavily on **which data ends up in the training vs test set**.  
- **Cross-validation** solves this by **splitting the data multiple times** and averaging results for a more reliable estimate.  

💡 *Analogy:* Testing a recipe multiple times on different groups of friends instead of relying on just one tasting session.  

---

## **2.2 K-Fold Cross-Validation**  
K-Fold Cross-Validation splits the dataset into **K equal parts (folds)**:

1. Use **K-1 folds** to train the model.  
2. Use the **remaining fold** to test the model.  
3. Repeat this process **K times**, each time using a different fold as the test set.  
4. Average the performance across all K runs → **robust estimate of model performance**.  

- Common choice: **K = 5 or 10**  
- Pros: More reliable than a single train-test split, especially on small datasets  

💡 *Example:* With 5-Fold CV, each fold is tested once → 5 performance scores → take the average.  

---

## **2.3 Stratified K-Fold**  
- Sometimes datasets are **imbalanced** (e.g., 90% class A, 10% class B).  
- Regular K-Fold may split data unevenly → some folds might have very few minority class samples.  
- **Stratified K-Fold** ensures **each fold preserves the class proportion** of the original dataset.  

💡 *Analogy:* Think of making sure each tasting group gets a **balanced mix of cookie types** instead of ending up with only chocolate chip cookies in one group.  

- In scikit-learn:

```python
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

# Module 3: Introduction to GridSearchCV

---

## **3.1 The Grid Search Concept**

**The Goal:**  
 We are **systematically defining a finite set of values** to test.

---

### 📖 Core Concept
Grid Search is an **exhaustive search algorithm**:

- You provide a list of hyperparameters and specific values to test.  
- It builds a **mathematical grid** of all possible combinations.  
- Each combination is evaluated to find the **best hyperparameters**.

---

## 3.2 How GridSearchCV Works (Grid Search + K-Fold CV)

**The Goal:**  
Must understand that **each combination is evaluated rigorously using Cross-Validation**.

---

### 📖 Core Concept
**GridSearchCV = Grid Search + Cross-Validation**  

- For **each hyperparameter combination**, it runs a **full K-Fold Cross-Validation**.  
- The **best parameters** are the ones with the **highest average score** across all folds.

---

### 💡 Analogy: Taste Test Panel
- One person tasting all meals → **biased opinion**.  
- 5 judges tasting all meals → **average score is fairer**.  
- Similarly, **5-Fold CV evaluates each combination on multiple folds** to ensure reliability.

---

### 🛠️ Step-by-Step
1. Pick **combination #1** from the grid.  
2. Split the training data into **K folds**.  
3. Train on **K-1 folds**, test on the remaining fold.  
4. Repeat **K times** → calculate **average score** for combination #1.  
5. Repeat steps 1–4 for **all combinations**.  
6. Compare all averages → pick the **best combination**.

---

# 📊 Manual Calculation of ROC-AUC

You are given:


actual = [0, 0, 1, 1, 1, 0, 0]

predicted = [0.1, 0.3, 0.4, 0.9, 0.76, 0.55, 0.2]


---

## 🎯 Step 1: Understand What AUC Means

**AUC (Area Under the Curve)** is:

> The probability that a randomly chosen positive example has a higher predicted score than a randomly chosen negative example.

Instead of constructing the ROC curve using thresholds, we compute AUC using **pairwise comparison**.

---

## 🔢 Step 2: Separate Positives and Negatives

### ✅ Positives (actual = 1)

Scores:


0.4, 0.9, 0.76


Total positives = **3**

---

### ❌ Negatives (actual = 0)

Scores:


0.1, 0.3, 0.55, 0.2


Total negatives = **4**

---

## 🔁 Step 3: Compare Every Positive vs Every Negative

Total comparisons:

$$
3 \times 4 = 12
$$

Now check whether:

$$
\text{positive score} > \text{negative score}
$$

---

### 🔹 Positive = 0.4

- 0.1 ✅  
- 0.3 ✅  
- 0.55 ❌  
- 0.2 ✅  

Wins = **3**

---

### 🔹 Positive = 0.9

- 0.1 ✅  
- 0.3 ✅  
- 0.55 ✅  
- 0.2 ✅  

Wins = **4**

---

### 🔹 Positive = 0.76

- 0.1 ✅  
- 0.3 ✅  
- 0.55 ✅  
- 0.2 ✅  

Wins = **4**

---

## 🧮 Step 4: Compute AUC

Total wins:

$$
3 + 4 + 4 = 11
$$

Total comparisons:

$$
12
$$

$$
\text{AUC} = \frac{11}{12} = 0.9167
$$

---

## ✅ Final Answer

$$
\boxed{\text{ROC-AUC} \approx 0.917}
$$

---

## 🧠 Interpretation

There is a **91.7\% probability** that a randomly chosen positive example has a higher predicted probability than a randomly chosen negative example.

This indicates a **strong classifier**.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFECV
from sklearn.metrics import roc_auc_score

In [ ]:
# Load dataset
digits = load_digits()

In [ ]:
X, y = digits.data, digits.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [10, 50, 100],
    'max_depth': [5, 10],
    'min_samples_split': [2, 5],
    'criterion': ['gini', 'entropy']
}

# Initialize RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,              # 5-Fold Cross Validation
    n_jobs=-1,         # Use all CPU cores
    verbose=2          # Prints progress
)

# Fit the Grid Search to your training data
grid_search.fit(X_train, y_train)

# Best combination found
print("Best Hyperparameters:", grid_search.best_params_)
print("Best Cross-Validation Score:", grid_search.best_score_)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.3s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.2s
Best Hyperparameters: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}
Best Cross-Validation Score: 0.9732672449401074

In [ ]:
# Predict on the test set
y_pred = grid_search.predict(X_test)
y_pred_proba = grid_search.predict_proba(X_test)

# Evaluate the model
roc_auc = roc_auc_score(y_test, y_pred_proba, multi_class='ovr')
print("ROC AUC Score on test data: ", roc_auc)

ROC AUC Score on test data:  0.9991453920527315

# data for testing

new_patient1 = np.array([
    [14.0, 20.0, 90.0, 600.0, 0.1, 0.2, 1.0, 15.0, 0.02, 0.03,
     0.3, 1.0, 2.0, 30.0, 0.006, 0.02, 0.03, 0.015, 0.02, 0.003,
     16.0, 25.0, 105.0, 700.0, 0.14, 0.35, 1.2, 20.0, 0.03, 0.04]
   
])

In [ ]:
# load the data for testing

In [110]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [111]:
from sklearn.datasets import load_iris

iris = load_iris()

In [112]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [113]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [114]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [115]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [116]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [117]:
#df['species'] = [iris.target_names[t] for t in iris.target]

In [118]:
df['species_num'] = iris.target

In [119]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species_num
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [120]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species_num        150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None

In [121]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species_num          0
dtype: int64

In [122]:
df.duplicated().sum()

np.int64(1)

In [123]:
df = df.drop_duplicates()

In [124]:
df.shape

(149, 5)

In [125]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species_num
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [126]:
X = df.drop(["species_num"], axis = 1)
y = df['species_num']

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [128]:
param_grid = {
    'n_estimators': [10, 50, 100],
    'max_depth': [5, 10],
    'min_samples_split': [2, 5],
    'criterion': ['gini', 'entropy']
}

#  Initialize and Run GridSearchCV
rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,              
    n_jobs=-1,         
    verbose=2          
)

# Fit the model to the training data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=10; total time=   0.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=5, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.0s

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'], 'max_depth': [5, 10],
                         'min_samples_split': [2, 5],
                         'n_estimators': [10, 50, 100]},
             verbose=2)

In [129]:
# Output Results
print("\n--- Results ---")
print("Best Hyperparameters:", grid_search.best_params_)
print("Best Cross-Validation Score:", grid_search.best_score_)

--- Results ---
Best Hyperparameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 50}
Best Cross-Validation Score: 0.9640316205533598